/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltp4j_Pair */

#ifndef _Included_edu_hit_ir_ltp4j_Pair
#define _Included_edu_hit_ir_ltp4j_Pair
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
