/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltp4j_NER */

#ifndef _Included_edu_hit_ir_ltp4j_NER
#define _Included_edu_hit_ir_ltp4j_NER
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltp4j_NER
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_NER_create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_hit_ir_ltp4j_NER
 * Method:    recognize
 * Signature: (Ljava/util/List;Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_NER_recognize
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltp4j_NER
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltp4j_NER_release
  (JNIEnv *, jobject);

/*
 * Class:     edu_hit_ir_ltp4j_NER
 * Method:    loaded
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltp4j_NER_loaded
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
